DROP TABLE IF EXISTS `customers`;

CREATE TABLE IF NOT EXISTS `customers` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(40) DEFAULT NULL,
    `surname` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS 'items';
CREATE TABLE IF NOT EXISTS 'ITEMS'(
id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(30) NOT NULL, value float FLOAT(5,2) NOT NULL);